name: Demo Sparse

on:
  workflow_dispatch:

jobs:
  sparse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docs
            .github

  full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
